package Vistas;

import AccesoADatos.*;
import Entidades.*;
import java.awt.*;
import javax.swing.*;

public class AdminABMUsuarios extends javax.swing.JPanel {

    Color violeta = new Color(153, 0, 153);
    Color naranja = new Color(255, 153, 0);

    public AdminABMUsuarios() {

        initComponents();

        //Carga los colores de los radioButtons y botones
       
        jbBuscar.setBackground(violeta);
        jbBuscar.setForeground(Color.white);
        jbLimpiar.setBackground(violeta);
        jbLimpiar.setForeground(Color.white);
        jbEliminar.setBackground(violeta);
        jbEliminar.setForeground(Color.white);
        jbCerrar.setBackground(violeta);
        jbCerrar.setForeground(Color.white);
        
        //Al inicio, inhabilita los botones 'Limpiar' (para cargar una nueva) y 'Elim.
        jbLimpiar.setEnabled(false);
        jbEliminar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBackground = new javax.swing.JPanel();
        jpLienzoDeTrabajo = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jbBuscar = new javax.swing.JButton();
        jtfIDUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jbLimpiar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbCerrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaDNI = new javax.swing.JTextArea();
        jbGuardar = new javax.swing.JButton();
        jlFotoDeFondo = new javax.swing.JLabel();
        jlCerrar = new javax.swing.JLabel();

        jpBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpLienzoDeTrabajo.setBackground(new java.awt.Color(255, 255, 255));
        jpLienzoDeTrabajo.setForeground(new java.awt.Color(0, 0, 0));
        jpLienzoDeTrabajo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTitulo.setBackground(new java.awt.Color(153, 0, 153));
        jlTitulo.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(153, 0, 153));
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("ABM de Usuarios");
        jpLienzoDeTrabajo.add(jlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 650, -1));

        jbBuscar.setText("Buscar por ID");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        jpLienzoDeTrabajo.add(jbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 150, -1));

        jtfIDUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jtfIDUsuario.setForeground(new java.awt.Color(153, 0, 153));
        jpLienzoDeTrabajo.add(jtfIDUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 190, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 153));
        jLabel7.setText("ID Usuario:");
        jpLienzoDeTrabajo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, -1));

        jtfNombre.setBackground(new java.awt.Color(255, 255, 255));
        jtfNombre.setForeground(new java.awt.Color(153, 0, 153));
        jpLienzoDeTrabajo.add(jtfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 660, 40));

        jbLimpiar.setBackground(new java.awt.Color(153, 0, 153));
        jbLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jbLimpiar.setText("Limpiar");
        jbLimpiar.setMaximumSize(new java.awt.Dimension(90, 32));
        jbLimpiar.setPreferredSize(new java.awt.Dimension(90, 32));
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });
        jpLienzoDeTrabajo.add(jbLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 120, -1));

        jbEliminar.setBackground(new java.awt.Color(153, 0, 153));
        jbEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jbEliminar.setText("Eliminar");
        jbEliminar.setPreferredSize(new java.awt.Dimension(90, 32));
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });
        jpLienzoDeTrabajo.add(jbEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 110, 30));

        jbCerrar.setBackground(new java.awt.Color(153, 0, 153));
        jbCerrar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jbCerrar.setText("X");
        jbCerrar.setPreferredSize(new java.awt.Dimension(90, 32));
        jbCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbCerrarMouseExited(evt);
            }
        });
        jbCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarActionPerformed(evt);
            }
        });
        jpLienzoDeTrabajo.add(jbCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 50, 40));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 153));
        jLabel9.setText("Nombre:");
        jpLienzoDeTrabajo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 80, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 153));
        jLabel10.setText("DNI");
        jpLienzoDeTrabajo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 80, -1));

        jtaDNI.setBackground(new java.awt.Color(255, 255, 255));
        jtaDNI.setColumns(20);
        jtaDNI.setForeground(new java.awt.Color(153, 0, 153));
        jtaDNI.setRows(5);
        jScrollPane2.setViewportView(jtaDNI);

        jpLienzoDeTrabajo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 410, 40));

        jbGuardar.setBackground(new java.awt.Color(153, 0, 153));
        jbGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jbGuardar.setText("Guardar");
        jbGuardar.setPreferredSize(new java.awt.Dimension(90, 32));
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        jpLienzoDeTrabajo.add(jbGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 110, -1));

        jpBackground.add(jpLienzoDeTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 810, 370));

        jlFotoDeFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Foto de base 980x654.png"))); // NOI18N
        jpBackground.add(jlFotoDeFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jlCerrar.setBackground(new java.awt.Color(153, 0, 153));
        jlCerrar.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jlCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jlCerrar.setText("X");
        jpBackground.add(jlCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 40, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed

        //Si no completa el campo 'ID Usuario'
        if (jtfIDUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe completar el campo 'ID Usuario'");

        } else {
            try {
                //Asignamos a una variable el dato ingresado en la vista
                int idUsuarioBuscado = Integer.parseInt(jtfIDUsuario.getText());

                //Instanciamos un usuario y usuarioData para usar luego
                UsuarioData usuarioD = new UsuarioData();
                Usuario usuarioBuscado = new Usuario();

                //Buscamos un usuario por su id usando buscar de usuarioData
                usuarioBuscado = usuarioD.buscarUsuarioPorID(idUsuarioBuscado);

                //Mostramos en la vista los datos del usuario encontrado excepto administrador (ya que sólo se considera al usuario 'admin'
                jtfIDUsuario.setText(Integer.toString(usuarioBuscado.getId_usuario()));
                jtfNombre.setText(usuarioBuscado.getNombre());
                jtaDNI.setText(Integer.toString(usuarioBuscado.getDni()));
                
                //Habilitamos los botones 'Limpiar' y 'Eliminar'
                jbLimpiar.setEnabled(true);
                jbEliminar.setEnabled(true);

            } catch (NumberFormatException nfe) {
                //si ingresa letras o símbolos
                JOptionPane.showMessageDialog(this, "Ingrese sólo números");
                jtfIDUsuario.setText("");
            } catch (NullPointerException npe) {
                JOptionPane.showMessageDialog(this,npe.getStackTrace());
            }
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        //Limpia la pantalla para cargar una mesa nueva
        jtfIDUsuario.setText("");
        jtfNombre.setText("");
        jtaDNI.setText("");
        jbLimpiar.setEnabled(false);
        jbEliminar.setEnabled(false);
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jbCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarActionPerformed
       AdminMenuPrincipal.volverALaFotoDeFondo();
    }//GEN-LAST:event_jbCerrarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        //Si el campo ID Usuario está vacío
        if (jtfIDUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete el campo 'ID Usuario'");

        } else {
            try {
                 //Creamos una variable con el ID tipeado en la vista
                int IDUsuarioAEliminar = Integer.parseInt(jtfIDUsuario.getText());
                
                //Instanciamos usuario y usuarioData para usar luego
                Usuario usuario = new Usuario();
                UsuarioData usuarioD = new UsuarioData();

                //Buscamos el usuario con ese id y lo enviamos al usuario ya creado
                usuario = usuarioD.buscarUsuarioPorID(IDUsuarioAEliminar);

                //Eliminamos el usuario llamando al método de usuarioData
                usuarioD.eliminarUsuario(usuario.getId_usuario());

                //Limpiamos los campos de la vista
                jtfIDUsuario.setText("");
                jtfNombre.setText("");
                jtaDNI.setText("");
                

            } catch (NumberFormatException ex) {
                //Si no tipea un documento en la vista
                JOptionPane.showMessageDialog(null, "Ingrese un ID Usuario");
            }
        }
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
         //Instanciamos usuarioData para usar luego
        UsuarioData usuarioD = new UsuarioData();

        if (jtfIDUsuario.getText().isEmpty()) {
            jtfIDUsuario.setText("-1");
        }

        try {
            //creamos las variables y asignamos los valores de la vista
            String nombreAGuardar = jtfNombre.getText();
            int dniAGuardar = Integer.parseInt(jtaDNI.getText());
            boolean administradorAGuardar = false;
            
            //Instanciamos un usuario con los parámetros anteriores
            Usuario usuarioAGuardar = new Usuario(nombreAGuardar, dniAGuardar, administradorAGuardar);

            //declaramos una variable bandera por si ya existe el id tipeado en vista
            boolean existeID = false;

            //Recorremos la lista de usuarios existentes
            for (Usuario existingUsuario : usuarioD.listarUsuario()) {

                if (existingUsuario.getId_usuario() == Integer.parseInt(jtfIDUsuario.getText())) {
                    //Si existe el usuario, seteamos el id para poder acceder al método modificar; si no existe se activa la bandera más abajo 
                    usuarioAGuardar.setId_usuario(usuarioD.buscarUsuarioPorID(Integer.parseInt(jtfIDUsuario.getText())).getId_usuario());
                    existeID = true;
                    break;
                }
            }
            //Si existe el usuario usa el método modificar; si no, guardar
            if (existeID == true) {
                usuarioD.modificarUsuario(usuarioAGuardar);
            } else {
                usuarioD.guardarUsuario(usuarioAGuardar);
            }

            //Habilitamos los botones 'Eliminar' y 'Limpiar'
            jbEliminar.setEnabled(true);
            jbLimpiar.setEnabled(true);
            
            //Limpiamos los campos de la vista
            jtfIDUsuario.setText("");
            jtfNombre.setText("");
            jtaDNI.setText("");
            

        } catch (NullPointerException ex) {
            //Si algún campo está vacío
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
        } catch (NumberFormatException ex) {
            //Si no usa números enteros en todos los campos
            JOptionPane.showMessageDialog(null, "Use sólo números enteros");
        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCerrarMouseEntered
        jbCerrar.setBackground(naranja);
        jbCerrar.setForeground(Color.white);
    }//GEN-LAST:event_jbCerrarMouseEntered

    private void jbCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCerrarMouseExited
       jbCerrar.setBackground(violeta);
       jbCerrar.setForeground(Color.white);
       
    }//GEN-LAST:event_jbCerrarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCerrar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JLabel jlCerrar;
    private javax.swing.JLabel jlFotoDeFondo;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JPanel jpBackground;
    private javax.swing.JPanel jpLienzoDeTrabajo;
    private javax.swing.JTextArea jtaDNI;
    private javax.swing.JTextField jtfIDUsuario;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables



}
