package Vistas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

public class AdminMenuPrincipal extends javax.swing.JFrame {

    Color violeta = new Color(153, 0, 153);
    Color naranja = new Color(255, 153, 0);

    public AdminMenuPrincipal() {
        initComponents();

        //Impide el cambio de tamaño de la ventana
        this.setResizable(false);

        //Abre la ventana del menú en el centro
        this.setLocationRelativeTo(null);

        //Establece el tono violeta del panel de menúes y de los botones
        jpMenu.setBackground(violeta);
        jbPorCategoria.setBackground(violeta);

        //Establece la fecha en formato [nombreDía dd MMMM aaaa]
        establecerFecha();

        //Establece la foto inicial de fondo
        initContent();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFondoBlanco = new javax.swing.JPanel();
        jpMenu = new javax.swing.JPanel();
        jlLogo = new javax.swing.JLabel();
        jbPorCategoria = new javax.swing.JButton();
        jbPorIngrediente = new javax.swing.JButton();
        jbPorHorario = new javax.swing.JButton();
        jbPorTipoDeCocina = new javax.swing.JButton();
        jbSinGluten = new javax.swing.JButton();
        jbBusquedaCombinada = new javax.swing.JButton();
        jbABMRecetas = new javax.swing.JButton();
        jbPorFormaDeCoccion = new javax.swing.JButton();
        jbABMUsuarios = new javax.swing.JButton();
        jpCabecera = new javax.swing.JPanel();
        jpContent = new javax.swing.JPanel();
        jlBienvenida = new javax.swing.JLabel();
        jlDia = new javax.swing.JLabel();
        jlVeganicemosElMundo = new javax.swing.JLabel();
        jbCerrarApp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jpFondoBlanco.setBackground(new java.awt.Color(255, 255, 255));

        jpMenu.setBackground(new java.awt.Color(153, 0, 153));
        jpMenu.setPreferredSize(new java.awt.Dimension(290, 750));

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo (1).png"))); // NOI18N

        jbPorCategoria.setBackground(new java.awt.Color(153, 0, 153));
        jbPorCategoria.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbPorCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jbPorCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/categoría de 50.png"))); // NOI18N
        jbPorCategoria.setText("   Por CATEGORÍA");
        jbPorCategoria.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jbPorCategoria.setBorderPainted(false);
        jbPorCategoria.setContentAreaFilled(false);
        jbPorCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPorCategoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbPorCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbPorCategoria.setIconTextGap(6);
        jbPorCategoria.setPreferredSize(new java.awt.Dimension(210, 40));
        jbPorCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbPorCategoriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbPorCategoriaMouseExited(evt);
            }
        });
        jbPorCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPorCategoriaActionPerformed(evt);
            }
        });

        jbPorIngrediente.setBackground(new java.awt.Color(153, 0, 153));
        jbPorIngrediente.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbPorIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        jbPorIngrediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ingrediente ppal de 50.png"))); // NOI18N
        jbPorIngrediente.setText("   Por INGREDIENTE");
        jbPorIngrediente.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jbPorIngrediente.setBorderPainted(false);
        jbPorIngrediente.setContentAreaFilled(false);
        jbPorIngrediente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPorIngrediente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbPorIngrediente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbPorIngrediente.setIconTextGap(6);
        jbPorIngrediente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbPorIngredienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbPorIngredienteMouseExited(evt);
            }
        });
        jbPorIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPorIngredienteActionPerformed(evt);
            }
        });

        jbPorHorario.setBackground(new java.awt.Color(153, 0, 153));
        jbPorHorario.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbPorHorario.setForeground(new java.awt.Color(255, 255, 255));
        jbPorHorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/horario de comida de 50.png"))); // NOI18N
        jbPorHorario.setText("   Por HORARIO");
        jbPorHorario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jbPorHorario.setBorderPainted(false);
        jbPorHorario.setContentAreaFilled(false);
        jbPorHorario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPorHorario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbPorHorario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbPorHorario.setIconTextGap(6);
        jbPorHorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbPorHorarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbPorHorarioMouseExited(evt);
            }
        });
        jbPorHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPorHorarioActionPerformed(evt);
            }
        });

        jbPorTipoDeCocina.setBackground(new java.awt.Color(153, 0, 153));
        jbPorTipoDeCocina.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbPorTipoDeCocina.setForeground(new java.awt.Color(255, 255, 255));
        jbPorTipoDeCocina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tipo de cocina de 50.png"))); // NOI18N
        jbPorTipoDeCocina.setText("   Por TIPO de COCINA");
        jbPorTipoDeCocina.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jbPorTipoDeCocina.setBorderPainted(false);
        jbPorTipoDeCocina.setContentAreaFilled(false);
        jbPorTipoDeCocina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPorTipoDeCocina.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbPorTipoDeCocina.setIconTextGap(6);
        jbPorTipoDeCocina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbPorTipoDeCocinaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbPorTipoDeCocinaMouseExited(evt);
            }
        });
        jbPorTipoDeCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPorTipoDeCocinaActionPerformed(evt);
            }
        });

        jbSinGluten.setBackground(new java.awt.Color(153, 0, 153));
        jbSinGluten.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbSinGluten.setForeground(new java.awt.Color(255, 255, 255));
        jbSinGluten.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sin gluten de 50.png"))); // NOI18N
        jbSinGluten.setText("   Sin GLUTEN");
        jbSinGluten.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jbSinGluten.setBorderPainted(false);
        jbSinGluten.setContentAreaFilled(false);
        jbSinGluten.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSinGluten.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbSinGluten.setIconTextGap(6);
        jbSinGluten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbSinGlutenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbSinGlutenMouseExited(evt);
            }
        });
        jbSinGluten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSinGlutenActionPerformed(evt);
            }
        });

        jbBusquedaCombinada.setBackground(new java.awt.Color(153, 0, 153));
        jbBusquedaCombinada.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbBusquedaCombinada.setForeground(new java.awt.Color(255, 255, 255));
        jbBusquedaCombinada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/búsqueda combinada de 50.png"))); // NOI18N
        jbBusquedaCombinada.setText("   Búsq. COMBINADA");
        jbBusquedaCombinada.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jbBusquedaCombinada.setBorderPainted(false);
        jbBusquedaCombinada.setContentAreaFilled(false);
        jbBusquedaCombinada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbBusquedaCombinada.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbBusquedaCombinada.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbBusquedaCombinada.setIconTextGap(6);
        jbBusquedaCombinada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbBusquedaCombinadaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbBusquedaCombinadaMouseExited(evt);
            }
        });
        jbBusquedaCombinada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBusquedaCombinadaActionPerformed(evt);
            }
        });

        jbABMRecetas.setBackground(new java.awt.Color(153, 0, 153));
        jbABMRecetas.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbABMRecetas.setForeground(new java.awt.Color(255, 255, 255));
        jbABMRecetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/administración de 50.png"))); // NOI18N
        jbABMRecetas.setText("ABM Recetas");
        jbABMRecetas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jbABMRecetas.setBorderPainted(false);
        jbABMRecetas.setContentAreaFilled(false);
        jbABMRecetas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbABMRecetas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbABMRecetas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbABMRecetas.setIconTextGap(16);
        jbABMRecetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbABMRecetasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbABMRecetasMouseExited(evt);
            }
        });
        jbABMRecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbABMRecetasActionPerformed(evt);
            }
        });

        jbPorFormaDeCoccion.setBackground(new java.awt.Color(153, 0, 153));
        jbPorFormaDeCoccion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbPorFormaDeCoccion.setForeground(new java.awt.Color(255, 255, 255));
        jbPorFormaDeCoccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/forma de coccion en 50.png"))); // NOI18N
        jbPorFormaDeCoccion.setText("   Por COCCIÓN");
        jbPorFormaDeCoccion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jbPorFormaDeCoccion.setBorderPainted(false);
        jbPorFormaDeCoccion.setContentAreaFilled(false);
        jbPorFormaDeCoccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPorFormaDeCoccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbPorFormaDeCoccion.setIconTextGap(6);
        jbPorFormaDeCoccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbPorFormaDeCoccionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbPorFormaDeCoccionMouseExited(evt);
            }
        });
        jbPorFormaDeCoccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPorFormaDeCoccionActionPerformed(evt);
            }
        });

        jbABMUsuarios.setBackground(new java.awt.Color(153, 0, 153));
        jbABMUsuarios.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbABMUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        jbABMUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/administración de 50.png"))); // NOI18N
        jbABMUsuarios.setText("ABM Usuarios");
        jbABMUsuarios.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jbABMUsuarios.setBorderPainted(false);
        jbABMUsuarios.setContentAreaFilled(false);
        jbABMUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbABMUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbABMUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbABMUsuarios.setIconTextGap(16);
        jbABMUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbABMUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbABMUsuariosMouseExited(evt);
            }
        });
        jbABMUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbABMUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jlLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbPorCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(jbPorIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPorHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPorTipoDeCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSinGluten, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBusquedaCombinada, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPorFormaDeCoccion, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbABMRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbABMUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jbPorCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPorIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jbPorHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jbPorTipoDeCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPorFormaDeCoccion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSinGluten, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jbBusquedaCombinada, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbABMRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbABMUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpCabecera.setBackground(new java.awt.Color(255, 153, 0));
        jpCabecera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpCabeceraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpContentLayout = new javax.swing.GroupLayout(jpContent);
        jpContent.setLayout(jpContentLayout);
        jpContentLayout.setHorizontalGroup(
            jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpContentLayout.setVerticalGroup(
            jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );

        jlBienvenida.setBackground(new java.awt.Color(255, 153, 0));
        jlBienvenida.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jlBienvenida.setForeground(new java.awt.Color(153, 0, 153));
        jlBienvenida.setText("Bienvenida/e/o a VACA, la primera app de cocina vegana");

        jlDia.setBackground(new java.awt.Color(255, 153, 0));
        jlDia.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jlDia.setForeground(new java.awt.Color(153, 0, 153));
        jlDia.setText("Hoy es ...");

        javax.swing.GroupLayout jpCabeceraLayout = new javax.swing.GroupLayout(jpCabecera);
        jpCabecera.setLayout(jpCabeceraLayout);
        jpCabeceraLayout.setHorizontalGroup(
            jpCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpCabeceraLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jpCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDia)
                    .addComponent(jlBienvenida))
                .addContainerGap(410, Short.MAX_VALUE))
        );
        jpCabeceraLayout.setVerticalGroup(
            jpCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCabeceraLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jlBienvenida)
                .addGap(49, 49, 49)
                .addComponent(jlDia)
                .addGap(65, 65, 65)
                .addComponent(jpContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jlVeganicemosElMundo.setBackground(new java.awt.Color(255, 255, 255));
        jlVeganicemosElMundo.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jlVeganicemosElMundo.setForeground(new java.awt.Color(153, 0, 153));
        jlVeganicemosElMundo.setText("¡¡¡ Veganicemos el mundo !!!");

        jbCerrarApp.setBackground(new java.awt.Color(153, 0, 153));
        jbCerrarApp.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbCerrarApp.setForeground(new java.awt.Color(255, 255, 255));
        jbCerrarApp.setText("X");
        jbCerrarApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbCerrarAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbCerrarAppMouseExited(evt);
            }
        });
        jbCerrarApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarAppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpFondoBlancoLayout = new javax.swing.GroupLayout(jpFondoBlanco);
        jpFondoBlanco.setLayout(jpFondoBlancoLayout);
        jpFondoBlancoLayout.setHorizontalGroup(
            jpFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoBlancoLayout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpFondoBlancoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jlVeganicemosElMundo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbCerrarApp, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        jpFondoBlancoLayout.setVerticalGroup(
            jpFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 1061, Short.MAX_VALUE)
            .addGroup(jpFondoBlancoLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jpFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlVeganicemosElMundo)
                    .addComponent(jbCerrarApp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondoBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondoBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void initContent() {

        volverALaFotoDeFondo();

    }

    private void establecerFecha() {

        //Establece la fecha de forma automática
        Date fecha = new Date(); //fecha y hora actual
        SimpleDateFormat sdf = new SimpleDateFormat("'Hoy es 'EEEE dd' de 'MMMM' de 'yyyy"); //formateo la fecha en una cadena
        jlDia.setText(sdf.format(fecha)); //seteo en el jLabel la cadena obtenida

    }

    private void jbPorCategoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPorCategoriaMouseEntered
        // Seteamos letras en naranja si se acerca el mouse
        jbPorCategoria.setForeground(naranja);
    }//GEN-LAST:event_jbPorCategoriaMouseEntered

    private void jbPorCategoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPorCategoriaMouseExited
        // Seteamos la vuelta al violeta y blanco cuando el mouse se aleja
        jbPorCategoria.setBackground(violeta);
        jbPorCategoria.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_jbPorCategoriaMouseExited

    private void jbPorCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPorCategoriaActionPerformed
        AdminBusquedaPorCategoria abpcat = new AdminBusquedaPorCategoria();
        abpcat.setSize(980, 654);
        abpcat.setLocation(0, 0);

        jpContent.removeAll();
        jpContent.add(abpcat, BorderLayout.CENTER);
        jpContent.revalidate();
        jpContent.repaint();
    }//GEN-LAST:event_jbPorCategoriaActionPerformed

    private void jbPorIngredienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPorIngredienteMouseEntered
        // Seteamos letras en naranja si se acerca el mouse
        jbPorIngrediente.setForeground(naranja);
    }//GEN-LAST:event_jbPorIngredienteMouseEntered

    private void jbPorIngredienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPorIngredienteMouseExited
        // Seteamos la vuelta al violeta y blanco cuando el mouse se aleja
        jbPorIngrediente.setBackground(violeta);
        jbPorIngrediente.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_jbPorIngredienteMouseExited

    private void jbPorIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPorIngredienteActionPerformed
        AdminBusquedaPorIngrediente abping = new AdminBusquedaPorIngrediente();
        abping.setSize(980, 654);
        abping.setLocation(0, 0);

        jpContent.removeAll();
        jpContent.add(abping, BorderLayout.CENTER);
        jpContent.revalidate();
        jpContent.repaint();
    }//GEN-LAST:event_jbPorIngredienteActionPerformed

    private void jbPorHorarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPorHorarioMouseEntered
        // Seteamos letras en naranja si se acerca el mouse
        jbPorHorario.setForeground(naranja);
    }//GEN-LAST:event_jbPorHorarioMouseEntered

    private void jbPorHorarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPorHorarioMouseExited
        // Seteamos la vuelta al violeta y blanco cuando el mouse se aleja
        jbPorHorario.setBackground(violeta);
        jbPorHorario.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_jbPorHorarioMouseExited

    private void jbPorHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPorHorarioActionPerformed
        AdminBusquedaPorHorario abphora = new AdminBusquedaPorHorario();
        abphora.setSize(980, 654);
        abphora.setLocation(0, 0);

        jpContent.removeAll();
        jpContent.add(abphora, BorderLayout.CENTER);
        jpContent.revalidate();
        jpContent.repaint();
    }//GEN-LAST:event_jbPorHorarioActionPerformed

    private void jbPorTipoDeCocinaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPorTipoDeCocinaMouseEntered
        // Seteamos letras en naranja si se acerca el mouse
        jbPorTipoDeCocina.setForeground(naranja);
    }//GEN-LAST:event_jbPorTipoDeCocinaMouseEntered

    private void jbPorTipoDeCocinaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPorTipoDeCocinaMouseExited
        // Seteamos la vuelta al violeta y blanco cuando el mouse se aleja
        jbPorTipoDeCocina.setBackground(violeta);
        jbPorTipoDeCocina.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_jbPorTipoDeCocinaMouseExited

    private void jbPorTipoDeCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPorTipoDeCocinaActionPerformed
        AdminBusquedaPorTipoDeCocina abpTipoCocina = new AdminBusquedaPorTipoDeCocina();
        abpTipoCocina.setSize(980, 654);
        abpTipoCocina.setLocation(0, 0);

        jpContent.removeAll();
        jpContent.add(abpTipoCocina, BorderLayout.CENTER);
        jpContent.revalidate();
        jpContent.repaint();
    }//GEN-LAST:event_jbPorTipoDeCocinaActionPerformed

    private void jbSinGlutenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSinGlutenMouseEntered
        // Seteamos letras en naranja si se acerca el mouse
        jbSinGluten.setForeground(naranja);
    }//GEN-LAST:event_jbSinGlutenMouseEntered

    private void jbSinGlutenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSinGlutenMouseExited
        // Seteamos la vuelta al violeta y blanco cuando el mouse se aleja
        jbSinGluten.setBackground(violeta);
        jbSinGluten.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_jbSinGlutenMouseExited

    private void jbSinGlutenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSinGlutenActionPerformed
        AdminBusquedaPorGluten abpgluten = new AdminBusquedaPorGluten();
        abpgluten.setSize(980, 654);
        abpgluten.setLocation(0, 0);

        jpContent.removeAll();
        jpContent.add(abpgluten, BorderLayout.CENTER);
        jpContent.revalidate();
        jpContent.repaint();
    }//GEN-LAST:event_jbSinGlutenActionPerformed

    private void jbBusquedaCombinadaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbBusquedaCombinadaMouseEntered
        // Seteamos letras en naranja si se acerca el mouse
        jbBusquedaCombinada.setForeground(naranja);
    }//GEN-LAST:event_jbBusquedaCombinadaMouseEntered

    private void jbBusquedaCombinadaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbBusquedaCombinadaMouseExited
        // Seteamos la vuelta al violeta y blanco cuando el mouse se aleja
        jbBusquedaCombinada.setBackground(violeta);
        jbBusquedaCombinada.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_jbBusquedaCombinadaMouseExited

    private void jbBusquedaCombinadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBusquedaCombinadaActionPerformed
        AdminBusquedaCombinada abcombi = new AdminBusquedaCombinada();
        abcombi.setSize(980, 654);
        abcombi.setLocation(0, 0);

        jpContent.removeAll();
        jpContent.add(abcombi, BorderLayout.CENTER);
        jpContent.revalidate();
        jpContent.repaint();
    }//GEN-LAST:event_jbBusquedaCombinadaActionPerformed

    private void jbABMRecetasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbABMRecetasMouseEntered
        // Seteamos letras en naranja si se acerca el mouse
        jbABMRecetas.setForeground(naranja);
    }//GEN-LAST:event_jbABMRecetasMouseEntered

    private void jbABMRecetasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbABMRecetasMouseExited
        // Seteamos la vuelta al violeta y blanco cuando el mouse se aleja
        jbABMRecetas.setBackground(violeta);
        jbABMRecetas.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_jbABMRecetasMouseExited

    private void jbABMRecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbABMRecetasActionPerformed
        AdminABMRecetas adm = new AdminABMRecetas();
        adm.setSize(980, 654);
        adm.setLocation(0, 0);

        jpContent.removeAll();
        jpContent.add(adm, BorderLayout.CENTER);
        jpContent.revalidate();
        jpContent.repaint();
    }//GEN-LAST:event_jbABMRecetasActionPerformed

    private void jbPorFormaDeCoccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPorFormaDeCoccionMouseEntered
       // Seteamos letras en naranja si se acerca el mouse
        jbPorFormaDeCoccion.setForeground(naranja);
    }//GEN-LAST:event_jbPorFormaDeCoccionMouseEntered

    private void jbPorFormaDeCoccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPorFormaDeCoccionMouseExited
        // Seteamos la vuelta al violeta y blanco cuando el mouse se aleja
        jbPorFormaDeCoccion.setBackground(violeta);
        jbPorFormaDeCoccion.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_jbPorFormaDeCoccionMouseExited

    private void jbPorFormaDeCoccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPorFormaDeCoccionActionPerformed
        AdminBusquedaPorFormaDeCoccion abpcoccion = new AdminBusquedaPorFormaDeCoccion();
        abpcoccion.setSize(980, 654);
        abpcoccion.setLocation(0, 0);

        jpContent.removeAll();
        jpContent.add(abpcoccion, BorderLayout.CENTER);
        jpContent.revalidate();
        jpContent.repaint();
    }//GEN-LAST:event_jbPorFormaDeCoccionActionPerformed

    private void jpCabeceraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCabeceraMouseClicked
        AdminPrincipal appal = new AdminPrincipal();
        appal.setSize(980, 654);
        appal.setLocation(0, 0);

        jpContent.removeAll();
        jpContent.add(appal, BorderLayout.CENTER);
        jpContent.revalidate();
        jpContent.repaint();
    }//GEN-LAST:event_jpCabeceraMouseClicked

    private void jbCerrarAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarAppActionPerformed
        //Llama al método para cerrar la aplicación completa
        cerrar();
    }//GEN-LAST:event_jbCerrarAppActionPerformed

    private void jbCerrarAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCerrarAppMouseEntered
        jbCerrarApp.setBackground(naranja);
        jbCerrarApp.setForeground(Color.white);
    }//GEN-LAST:event_jbCerrarAppMouseEntered

    private void jbCerrarAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCerrarAppMouseExited
        jbCerrarApp.setBackground(violeta);
        jbCerrarApp.setForeground(Color.white);
    }//GEN-LAST:event_jbCerrarAppMouseExited

    private void jbABMUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbABMUsuariosMouseEntered
        // Seteamos letras en naranja si se acerca el mouse
        jbABMUsuarios.setForeground(naranja);
    }//GEN-LAST:event_jbABMUsuariosMouseEntered

    private void jbABMUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbABMUsuariosMouseExited
        // Seteamos la vuelta al violeta y blanco cuando el mouse se aleja
        jbABMUsuarios.setBackground(violeta);
        jbABMUsuarios.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_jbABMUsuariosMouseExited

    private void jbABMUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbABMUsuariosActionPerformed
        AdminABMUsuarios adUsuarios = new AdminABMUsuarios();
        adUsuarios.setSize(980, 654);
        adUsuarios.setLocation(0, 0);

        jpContent.removeAll();
        jpContent.add(adUsuarios, BorderLayout.CENTER);
        jpContent.revalidate();
        jpContent.repaint();
    }//GEN-LAST:event_jbABMUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbABMRecetas;
    private javax.swing.JButton jbABMUsuarios;
    private javax.swing.JButton jbBusquedaCombinada;
    private javax.swing.JButton jbCerrarApp;
    private javax.swing.JButton jbPorCategoria;
    private javax.swing.JButton jbPorFormaDeCoccion;
    private javax.swing.JButton jbPorHorario;
    private javax.swing.JButton jbPorIngrediente;
    private javax.swing.JButton jbPorTipoDeCocina;
    private javax.swing.JButton jbSinGluten;
    private javax.swing.JLabel jlBienvenida;
    private javax.swing.JLabel jlDia;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel jlVeganicemosElMundo;
    private javax.swing.JPanel jpCabecera;
    public static javax.swing.JPanel jpContent;
    private javax.swing.JPanel jpFondoBlanco;
    private javax.swing.JPanel jpMenu;
    // End of variables declaration//GEN-END:variables

    public static void volverALaFotoDeFondo(){
        AdminPrincipal appal = new AdminPrincipal();
        appal.setSize(980, 654);
        appal.setLocation(0, 0);

        jpContent.removeAll();
        jpContent.add(appal, BorderLayout.CENTER);
        jpContent.revalidate();
        jpContent.repaint();
    
    }

    public void cerrar() {
        //Establece los nombre de los dos botones del JOptionPane
        String botones[] = {"Cerrar", "Cancelar"};

        //Asigna el JOptionPane a una variable y si elige 'si'...
        int eleccion = JOptionPane.showOptionDialog(this, "¿Desea cerrar la aplicación?", "Salir", 0, 0, null, botones, this);

        if (eleccion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

}
