
package Vistas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;


public class MenuPrincipal extends javax.swing.JFrame {

    Color violeta = new Color(153,0,153);
    Color naranja = new Color(255,153,0);
    
   
    public MenuPrincipal() {
        initComponents();
        
        //Establece el tono violeta del panel de menúes y de los botones
        jpMenu.setBackground(violeta);
        jbPorCategoria.setBackground(violeta);

        //Establece la fecha de forma automática
        Date fecha = new Date(); //fecha y hora actual
        SimpleDateFormat sdf = new SimpleDateFormat("'Hoy es 'EEEE dd' de 'MMMM' de 'yyyy"); //formateo la fecha en una cadena
        jlDia.setText(sdf.format(fecha)); //seteo en el jLabel la cadena obtenida
   
        ContenidoInicial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpEscritorio = new javax.swing.JPanel();
        jpMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jbPorIngrediente = new javax.swing.JButton();
        jbPorCategoria = new javax.swing.JButton();
        jbPorHorario = new javax.swing.JButton();
        jbPorTipoDeCocina = new javax.swing.JButton();
        jbAdministracion = new javax.swing.JButton();
        jbSinGluten = new javax.swing.JButton();
        jbBusquedaCombinada = new javax.swing.JButton();
        jpCabecera = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlDia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jpFondo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpEscritorio.setBackground(new java.awt.Color(255, 255, 255));
        jpEscritorio.setPreferredSize(new java.awt.Dimension(1310, 710));

        jpMenu.setBackground(new java.awt.Color(153, 0, 153));
        jpMenu.setPreferredSize(new java.awt.Dimension(270, 640));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo (1).png"))); // NOI18N

        jbPorIngrediente.setBackground(new java.awt.Color(153, 0, 153));
        jbPorIngrediente.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbPorIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        jbPorIngrediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ingrediente ppal de 50.png"))); // NOI18N
        jbPorIngrediente.setText("   Por INGREDIENTE");
        jbPorIngrediente.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jbPorIngrediente.setBorderPainted(false);
        jbPorIngrediente.setContentAreaFilled(false);
        jbPorIngrediente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPorIngrediente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbPorIngrediente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbPorIngrediente.setIconTextGap(6);
        jbPorIngrediente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbPorIngredienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbPorIngredienteMouseExited(evt);
            }
        });
        jbPorIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPorIngredienteActionPerformed(evt);
            }
        });

        jbPorCategoria.setBackground(new java.awt.Color(153, 0, 153));
        jbPorCategoria.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbPorCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jbPorCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/categoría de 50.png"))); // NOI18N
        jbPorCategoria.setText("   Por CATEGORÍA");
        jbPorCategoria.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jbPorCategoria.setBorderPainted(false);
        jbPorCategoria.setContentAreaFilled(false);
        jbPorCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPorCategoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbPorCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbPorCategoria.setIconTextGap(6);
        jbPorCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbPorCategoriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbPorCategoriaMouseExited(evt);
            }
        });
        jbPorCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPorCategoriaActionPerformed(evt);
            }
        });

        jbPorHorario.setBackground(new java.awt.Color(153, 0, 153));
        jbPorHorario.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbPorHorario.setForeground(new java.awt.Color(255, 255, 255));
        jbPorHorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/horario de comida de 50.png"))); // NOI18N
        jbPorHorario.setText("   Por HORARIO");
        jbPorHorario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jbPorHorario.setBorderPainted(false);
        jbPorHorario.setContentAreaFilled(false);
        jbPorHorario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPorHorario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbPorHorario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbPorHorario.setIconTextGap(6);
        jbPorHorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbPorHorarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbPorHorarioMouseExited(evt);
            }
        });
        jbPorHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPorHorarioActionPerformed(evt);
            }
        });

        jbPorTipoDeCocina.setBackground(new java.awt.Color(153, 0, 153));
        jbPorTipoDeCocina.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbPorTipoDeCocina.setForeground(new java.awt.Color(255, 255, 255));
        jbPorTipoDeCocina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tipo de cocina de 50.png"))); // NOI18N
        jbPorTipoDeCocina.setText("   Por TIPO de COCINA");
        jbPorTipoDeCocina.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jbPorTipoDeCocina.setBorderPainted(false);
        jbPorTipoDeCocina.setContentAreaFilled(false);
        jbPorTipoDeCocina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPorTipoDeCocina.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbPorTipoDeCocina.setIconTextGap(6);
        jbPorTipoDeCocina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbPorTipoDeCocinaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbPorTipoDeCocinaMouseExited(evt);
            }
        });
        jbPorTipoDeCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPorTipoDeCocinaActionPerformed(evt);
            }
        });

        jbAdministracion.setBackground(new java.awt.Color(153, 0, 153));
        jbAdministracion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbAdministracion.setForeground(new java.awt.Color(255, 255, 255));
        jbAdministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/administración de 50.png"))); // NOI18N
        jbAdministracion.setText("   ADMINISTRACIÓN");
        jbAdministracion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jbAdministracion.setBorderPainted(false);
        jbAdministracion.setContentAreaFilled(false);
        jbAdministracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbAdministracion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbAdministracion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbAdministracion.setIconTextGap(6);
        jbAdministracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbAdministracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbAdministracionMouseExited(evt);
            }
        });
        jbAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdministracionActionPerformed(evt);
            }
        });

        jbSinGluten.setBackground(new java.awt.Color(153, 0, 153));
        jbSinGluten.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbSinGluten.setForeground(new java.awt.Color(255, 255, 255));
        jbSinGluten.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sin gluten de 50.png"))); // NOI18N
        jbSinGluten.setText("   Sin GLUTEN");
        jbSinGluten.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jbSinGluten.setBorderPainted(false);
        jbSinGluten.setContentAreaFilled(false);
        jbSinGluten.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSinGluten.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbSinGluten.setIconTextGap(6);
        jbSinGluten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbSinGlutenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbSinGlutenMouseExited(evt);
            }
        });
        jbSinGluten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSinGlutenActionPerformed(evt);
            }
        });

        jbBusquedaCombinada.setBackground(new java.awt.Color(153, 0, 153));
        jbBusquedaCombinada.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbBusquedaCombinada.setForeground(new java.awt.Color(255, 255, 255));
        jbBusquedaCombinada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/búsqueda combinada de 50.png"))); // NOI18N
        jbBusquedaCombinada.setText("   Búsq. COMBINADA");
        jbBusquedaCombinada.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jbBusquedaCombinada.setBorderPainted(false);
        jbBusquedaCombinada.setContentAreaFilled(false);
        jbBusquedaCombinada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbBusquedaCombinada.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbBusquedaCombinada.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbBusquedaCombinada.setIconTextGap(6);
        jbBusquedaCombinada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbBusquedaCombinadaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbBusquedaCombinadaMouseExited(evt);
            }
        });
        jbBusquedaCombinada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBusquedaCombinadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel3))
            .addComponent(jbPorCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jbPorIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jbPorHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jbPorTipoDeCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jbSinGluten, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jbBusquedaCombinada, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jbAdministracion, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jbPorCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jbPorIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jbPorHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jbPorTipoDeCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jbSinGluten, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jbBusquedaCombinada, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jbAdministracion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpCabecera.setBackground(new java.awt.Color(255, 153, 0));
        jpCabecera.setPreferredSize(new java.awt.Dimension(750, 150));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Bienvenida/e/o a VACA, la primera app de cocina vegana");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jlDia.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jlDia.setForeground(new java.awt.Color(153, 0, 153));

        javax.swing.GroupLayout jpCabeceraLayout = new javax.swing.GroupLayout(jpCabecera);
        jpCabecera.setLayout(jpCabeceraLayout);
        jpCabeceraLayout.setHorizontalGroup(
            jpCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCabeceraLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpCabeceraLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jlDia))
            .addGroup(jpCabeceraLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpCabeceraLayout.setVerticalGroup(
            jpCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCabeceraLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(jlDia)
                .addGap(51, 51, 51)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setBackground(new java.awt.Color(153, 0, 153));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("¡Veganicemos el mundo!");

        javax.swing.GroupLayout jpFondoLayout = new javax.swing.GroupLayout(jpFondo);
        jpFondo.setLayout(jpFondoLayout);
        jpFondoLayout.setHorizontalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpFondoLayout.setVerticalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpEscritorioLayout = new javax.swing.GroupLayout(jpEscritorio);
        jpEscritorio.setLayout(jpEscritorioLayout);
        jpEscritorioLayout.setHorizontalGroup(
            jpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEscritorioLayout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEscritorioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, 1042, Short.MAX_VALUE))))
        );
        jpEscritorioLayout.setVerticalGroup(
            jpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
            .addGroup(jpEscritorioLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addGroup(jpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEscritorioLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jpCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1312, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEscritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbPorIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPorIngredienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbPorIngredienteActionPerformed

    private void jbPorCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPorCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbPorCategoriaActionPerformed

    private void jbAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdministracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAdministracionActionPerformed

    private void jbPorHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPorHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbPorHorarioActionPerformed

    private void jbPorTipoDeCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPorTipoDeCocinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbPorTipoDeCocinaActionPerformed

    private void jbSinGlutenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSinGlutenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSinGlutenActionPerformed

    private void jbBusquedaCombinadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBusquedaCombinadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbBusquedaCombinadaActionPerformed

    private void jbPorCategoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPorCategoriaMouseEntered
        // Seteamos letras en naranja si se acerca el mouse
        jbPorCategoria.setForeground(naranja);
    }//GEN-LAST:event_jbPorCategoriaMouseEntered

    private void jbPorCategoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPorCategoriaMouseExited
        // Seteamos la vuelta al violeta y blanco cuando el mouse se aleja
        jbPorCategoria.setBackground(violeta);
        jbPorCategoria.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_jbPorCategoriaMouseExited

    private void jbPorIngredienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPorIngredienteMouseEntered
        // Seteamos letras en naranja si se acerca el mouse
        jbPorIngrediente.setForeground(naranja);
    }//GEN-LAST:event_jbPorIngredienteMouseEntered

    private void jbPorIngredienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPorIngredienteMouseExited
        // Seteamos la vuelta al violeta y blanco cuando el mouse se aleja
        jbPorIngrediente.setBackground(violeta);
        jbPorIngrediente.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_jbPorIngredienteMouseExited

    private void jbPorHorarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPorHorarioMouseEntered
        // Seteamos letras en naranja si se acerca el mouse
        jbPorHorario.setForeground(naranja);
    }//GEN-LAST:event_jbPorHorarioMouseEntered

    private void jbPorHorarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPorHorarioMouseExited
        // Seteamos la vuelta al violeta y blanco cuando el mouse se aleja
        jbPorHorario.setBackground(violeta);
        jbPorHorario.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_jbPorHorarioMouseExited

    private void jbPorTipoDeCocinaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPorTipoDeCocinaMouseEntered
         // Seteamos letras en naranja si se acerca el mouse
        jbPorTipoDeCocina.setForeground(naranja);
    }//GEN-LAST:event_jbPorTipoDeCocinaMouseEntered

    private void jbPorTipoDeCocinaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPorTipoDeCocinaMouseExited
        // Seteamos la vuelta al violeta y blanco cuando el mouse se aleja
        jbPorTipoDeCocina.setBackground(violeta);
        jbPorTipoDeCocina.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_jbPorTipoDeCocinaMouseExited

    private void jbSinGlutenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSinGlutenMouseEntered
        // Seteamos letras en naranja si se acerca el mouse
        jbSinGluten.setForeground(naranja);
    }//GEN-LAST:event_jbSinGlutenMouseEntered

    private void jbSinGlutenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSinGlutenMouseExited
        // Seteamos la vuelta al violeta y blanco cuando el mouse se aleja
        jbSinGluten.setBackground(violeta);
        jbSinGluten.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_jbSinGlutenMouseExited

    private void jbBusquedaCombinadaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbBusquedaCombinadaMouseEntered
        // Seteamos letras en naranja si se acerca el mouse
        jbBusquedaCombinada.setForeground(naranja);
    }//GEN-LAST:event_jbBusquedaCombinadaMouseEntered

    private void jbBusquedaCombinadaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbBusquedaCombinadaMouseExited
        // Seteamos la vuelta al violeta y blanco cuando el mouse se aleja
        jbBusquedaCombinada.setBackground(violeta);
        jbBusquedaCombinada.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_jbBusquedaCombinadaMouseExited

    private void jbAdministracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAdministracionMouseEntered
        // Seteamos letras en naranja si se acerca el mouse
        jbAdministracion.setForeground(naranja);
    }//GEN-LAST:event_jbAdministracionMouseEntered

    private void jbAdministracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAdministracionMouseExited
        // Seteamos la vuelta al violeta y blanco cuando el mouse se aleja
        jbAdministracion.setBackground(violeta);
        jbAdministracion.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_jbAdministracionMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbAdministracion;
    private javax.swing.JButton jbBusquedaCombinada;
    private javax.swing.JButton jbPorCategoria;
    private javax.swing.JButton jbPorHorario;
    private javax.swing.JButton jbPorIngrediente;
    private javax.swing.JButton jbPorTipoDeCocina;
    private javax.swing.JButton jbSinGluten;
    private javax.swing.JLabel jlDia;
    private javax.swing.JPanel jpCabecera;
    private javax.swing.JPanel jpEscritorio;
    private javax.swing.JPanel jpFondo;
    private javax.swing.JPanel jpMenu;
    // End of variables declaration//GEN-END:variables

    public void ContenidoInicial(){
        FotoDeFondo fotoInicial = new FotoDeFondo();
        fotoInicial.setSize(1044, 697);
        fotoInicial.setLocation(0,0);
        
        jpFondo.removeAll();
        jpFondo.add(fotoInicial,BorderLayout.CENTER);
        jpFondo.revalidate();
        jpFondo.repaint();
    
    
}





}
