package Vistas;

import AccesoADatos.*;
import Entidades.*;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.JOptionPane;

public class RegistroUsuarioNuevo extends javax.swing.JFrame {

    //Defino dos variables que identificarán la posición del cursor del mouse para poder arrastrar la ventana
    int xMouse, yMouse;

    //Defino los dos colores principales
    Color violeta = new Color(153, 0, 153);
    Color naranja = new Color(255, 153, 0);

    //atributo común a todos los Data
    private Connection con = null;

    public RegistroUsuarioNuevo() {
        initComponents();

        //Abre la ventana del menú en el centro
        this.setLocationRelativeTo(null);

        //Establece el tamaño de la ventana al ejecutar
        this.setSize(860, 610);
        
        //inicializa la conexión, la variable 'con'
        con = Conexion.getConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jpCabecera = new javax.swing.JPanel();
        jlExit = new javax.swing.JLabel();
        jlLogo = new javax.swing.JLabel();
        jlFotoCortada = new javax.swing.JLabel();
        jlIniciarSesion = new javax.swing.JLabel();
        jlContrasenia = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jSeparador1 = new javax.swing.JSeparator();
        jtfUsuario = new javax.swing.JTextField();
        jSeparador2 = new javax.swing.JSeparator();
        jpfContrasenia = new javax.swing.JPasswordField();
        jbVolver = new javax.swing.JButton();
        jbRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(153, 0, 153));
        background.setMaximumSize(new java.awt.Dimension(860, 610));
        background.setName("Login"); // NOI18N
        background.setPreferredSize(new java.awt.Dimension(860, 600));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpCabecera.setBackground(new java.awt.Color(51, 51, 51));
        jpCabecera.setForeground(new java.awt.Color(51, 51, 51));
        jpCabecera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpCabeceraMouseDragged(evt);
            }
        });
        jpCabecera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpCabeceraMousePressed(evt);
            }
        });
        jpCabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlExit.setBackground(new java.awt.Color(255, 153, 0));
        jlExit.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jlExit.setForeground(new java.awt.Color(0, 0, 0));
        jlExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlExit.setText("X");
        jlExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlExit.setOpaque(true);
        jlExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlExitMouseExited(evt);
            }
        });
        jpCabecera.add(jlExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 70, 60));

        background.add(jpCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 60));

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo (1).png"))); // NOI18N
        background.add(jlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 180, 230));

        jlFotoCortada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver-arriba-verduras-mesa-madera 1 chiquitita (1).png"))); // NOI18N
        jlFotoCortada.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        background.add(jlFotoCortada, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 360, 600));

        jlIniciarSesion.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jlIniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        jlIniciarSesion.setText("REGISTRARSE");
        background.add(jlIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jlContrasenia.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jlContrasenia.setForeground(new java.awt.Color(0, 0, 0));
        jlContrasenia.setText("CONTRASEÑA");
        background.add(jlContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 60));

        jlUsuario.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jlUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jlUsuario.setText("USUARIO");
        background.add(jlUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 60));
        background.add(jSeparador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 390, 50));

        jtfUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jtfUsuario.setForeground(new java.awt.Color(153, 153, 153));
        jtfUsuario.setText("Ingrese el nombre de usuario");
        jtfUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtfUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtfUsuarioMousePressed(evt);
            }
        });
        background.add(jtfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 390, 60));
        background.add(jSeparador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 390, 50));

        jpfContrasenia.setBackground(new java.awt.Color(255, 255, 255));
        jpfContrasenia.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jpfContrasenia.setForeground(new java.awt.Color(153, 153, 153));
        jpfContrasenia.setText("***************");
        jpfContrasenia.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jpfContrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpfContraseniaMousePressed(evt);
            }
        });
        background.add(jpfContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 390, 60));

        jbVolver.setBackground(new java.awt.Color(153, 0, 153));
        jbVolver.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jbVolver.setForeground(new java.awt.Color(255, 255, 255));
        jbVolver.setText("VOLVER");
        jbVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbVolverMouseExited(evt);
            }
        });
        background.add(jbVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 140, 80));

        jbRegistrar.setBackground(new java.awt.Color(153, 0, 153));
        jbRegistrar.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jbRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        jbRegistrar.setText("REGISTRAR");
        jbRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbRegistrarMouseExited(evt);
            }
        });
        background.add(jbRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 140, 80));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpCabeceraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCabeceraMousePressed
        //Le doy los valores a x e y 
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jpCabeceraMousePressed

    private void jpCabeceraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCabeceraMouseDragged
        //Definimos dos variables que identifican la posición en pantalla
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        //Establecemos por diferencia para que el movimiento sea fluido
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jpCabeceraMouseDragged

    private void jlExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlExitMouseClicked
        //Invisibiliza, deselecciona y cierra la ventana
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jlExitMouseClicked

    private void jlExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlExitMouseEntered
        // Seteamos color violeta si se acerca el mouse
        jlExit.setBackground(violeta);
        jlExit.setForeground(Color.white);
    }//GEN-LAST:event_jlExitMouseEntered

    private void jlExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlExitMouseExited
        // Seteamos la vuelta al naranja cuando el mouse se aleja
        jlExit.setBackground(naranja);
        jlExit.setForeground(Color.black);
    }//GEN-LAST:event_jlExitMouseExited

    private void jtfUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfUsuarioMousePressed
        // Establece los campos por defecto
        if (jtfUsuario.getText().equals("Ingrese el nombre de usuario")) {
            jtfUsuario.setText("");
            jtfUsuario.setForeground(Color.black);
        }
        if (String.valueOf(jpfContrasenia.getPassword()).isEmpty()) {
            jpfContrasenia.setText("************");
            jpfContrasenia.setForeground(Color.gray);
        }

    }//GEN-LAST:event_jtfUsuarioMousePressed

    private void jpfContraseniaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpfContraseniaMousePressed
        // Establece los campos por defecto
        if (String.valueOf(jpfContrasenia.getPassword()).equals("************")) {
            jpfContrasenia.setText("");
            jpfContrasenia.setForeground(Color.black);
        }
        if (jtfUsuario.getText().isEmpty()) {
            jtfUsuario.setText("Ingrese el nombre de usuario");
            jtfUsuario.setForeground(Color.gray);
        }

    }//GEN-LAST:event_jpfContraseniaMousePressed

    private void jbVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbVolverMouseClicked
//        //Invisibiliza, deselecciona y cierra la ventana
//        this.dispose();
        Login login = new Login();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_jbVolverMouseClicked

    private void jbRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRegistrarMouseClicked
        UsuarioData usuarioD = new UsuarioData();

        try {
            //creamos las variables y asignamos los valores tipeados en la vista

            if (jtfUsuario.getText().equals("Ingrese el nombre de usuario") || jpfContrasenia.equals("***************")) {
                JOptionPane.showMessageDialog(null, "Complete los campos");
            } else {
                if (!validarString(jtfUsuario.getText().trim())) {
                    JOptionPane.showMessageDialog(null, "El campo 'usuario' sólo acepta letras");

                } else {
                    String usuarioAGuardar = jtfUsuario.getText();
                    int dniAGuardar = Integer.valueOf(jpfContrasenia.getText());
                    boolean administradorAGuardar = false;

                    //Instanciamos un usuario con los parámetros anteriores
                    Usuario usu = new Usuario(usuarioAGuardar, dniAGuardar, administradorAGuardar);

                    //declaramos una variable bandera por si ya existe el id tipeado en vista
                    boolean existeID = false;

                    //Recorremos la lista de usuarios existentes
                    for (Usuario existingUsuario : usuarioD.listarUsuario()) {

                        if (existingUsuario.getNombre().equals(usu.getNombre()) && existingUsuario.getDni() == usu.getDni()) {
                            //Si existe el usuario, seteamos el id para poder acceder al método modificar; si no existe se activa la bandera más abajo 

                            existeID = true;
                            break;
                        }
                    }
                    //Si existe el usuario usa el método modificarUsuario; si no, guardarUsuario
                    if (existeID == true) {
                        JOptionPane.showMessageDialog(null, "El usuario ya está registrado");
                    } else {
                        usuarioD.guardarUsuario(usu);
                    }
                }

            }

            //Limpiamos los textField luego de registrar.    
            jtfUsuario.setText("Ingrese el nombre de usuario");
            jtfUsuario.setForeground(Color.gray);

            jpfContrasenia.setText("***************");
            jpfContrasenia.setForeground(Color.gray);

        } catch (NullPointerException ex) {
            //Si algún campo está vacío
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
        }

    }//GEN-LAST:event_jbRegistrarMouseClicked

    private void jbVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbVolverMouseEntered
        jbVolver.setBackground(naranja);
        jbVolver.setForeground(Color.black);
    }//GEN-LAST:event_jbVolverMouseEntered

    private void jbVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbVolverMouseExited
        jbVolver.setBackground(violeta);
        jbVolver.setForeground(Color.white);
    }//GEN-LAST:event_jbVolverMouseExited

    private void jbRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRegistrarMouseEntered
        jbRegistrar.setBackground(naranja);
        jbRegistrar.setForeground(Color.black);
    }//GEN-LAST:event_jbRegistrarMouseEntered

    private void jbRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRegistrarMouseExited
        jbRegistrar.setBackground(violeta);
        jbRegistrar.setForeground(Color.white);
    }//GEN-LAST:event_jbRegistrarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarioNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarioNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarioNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarioNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuarioNuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JSeparator jSeparador1;
    private javax.swing.JSeparator jSeparador2;
    private javax.swing.JButton jbRegistrar;
    private javax.swing.JButton jbVolver;
    private javax.swing.JLabel jlContrasenia;
    private javax.swing.JLabel jlExit;
    private javax.swing.JLabel jlFotoCortada;
    private javax.swing.JLabel jlIniciarSesion;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JPanel jpCabecera;
    private javax.swing.JPasswordField jpfContrasenia;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables

    public static boolean validarString(String datos) {
        return datos.matches("[a-zA-Z]*");
    }

}
