package Entidades;

public enum Categoria {

    AGRIDULCE,
    ARROCES_GUISOS_SALTEADOS_RELLENOS,
    BURGERS_SEITAN_MILANESAS,
    DULCES_TRUFAS,
    ENSALADAS,
    LICORES,
    PANES,
    PARRILLADA_EMPANADAS_BROCHETTES,
    PROBIOTICOS_ESCABECHES,
    QUESOS_PATES,
    SALSAS,
    SNACKS_FINGERFOOD,
    SMOOTHIES_LECHES,
    TARTAS_TORTILLAS,
    TOFU,
    TORTAS_MUFFINS;
    

}
